### ISSUE TITLE
Помилка з svg файлами

### ISSUE THREAD

**Issue by Co1oR** [Natus-Vincere-Programming/MindGlow-application#11]
Коли я намагаємюся імпортувати svg файл в код, він не працює. А коли я створив свій проект тобто index.html все заробило і я просто не знаю шо робити в такій ситуації. 1) Це напряму вставляти їх в код 2) Це створити typescript файл в якому оголошувати всі svg в string.

**Comment by Xemii16** [comment]
А ти вставляєш в черег тег <svg> чи <img>?

**Comment by Co1oR** [comment]
через тег працює але там 3 рядка кода а <img> не працює

**Comment by Co1oR** [comment]
але саме головне шо в index.html все працює

**Comment by Co1oR** [comment]
Проблема вирішена. Треба було просто дати доступ до svg картинки в файлі angular.json в assets вказати шлях до картинки
