### ISSUE TITLE
Навігаційний бар

### ISSUE THREAD

**Issue by Xemii16** [Natus-Vincere-Programming/MindGlow-application#13]
**Опишіть що ви хочете додати?**
Потрібно додати навігаційний бар

**Опишіть як ви хочете її додати?**
Зробити копію з фігми з текстом і без

**Comment by Xemii16** [comment]
[Side navigation ](https://www.figma.com/design/I5FY5LynQRYEGbldO2objI/Site?node-id=192-548&t=odtOgROCrTPoIBes-0)

**Comment by ProgramMen** [comment]
Основні компоненти готові, але необхідно добавити шрифт
