### ISSUE TITLE
side navigation icon fix

### ISSUE THREAD

**Issue by ProgramMen** [Natus-Vincere-Programming/MindGlow-application#20]
Необхідно виправити icon в side navigation bar component

**Comment by ProgramMen** [comment]
icon в side navigation bar component було замінено і виправлено 
+виправлено розміщення

**Comment by ProgramMen** [comment]
Нове завдання добавити анімацію

**Comment by Xemii16** [comment]
- [ ] Зробити, щоб текст зміщувався вправа, а не вниз 
![image](https://github.com/Natus-Vincere-Programming/MindGlow-application/assets/113195769/9ca84f33-9c44-4dd2-9654-51c12368b622)

**Comment by ProgramMen** [comment]
На рахунок першого пункту зі зміщенням тексту вправо, тепер текст в один рядок також зайве вирізається і замінюється 3 крапками

**Comment by Xemii16** [comment]
От до речі питання, а чи є сенс ставити 3 крапки? Можливо все-таки краще щоб текст зміщувався вниз, але зі збільшення розмірів компонента?
