### ISSUE TITLE
Прапорці

### ISSUE THREAD

**Issue by Co1oR** [Natus-Vincere-Programming/MindGlow-application#3]
Хочу створити checkbox

**Comment by Xemii16** [comment]
Чекбокси будуть фіксовані - 20х20 пікселів

**Comment by nazor1k** [comment]
Чекбокси мають бути маштабовані для майбутнього апгрейду

**Comment by Xemii16** [comment]
> Чекбокси мають бути маштабовані для майбутнього апгрейду

Чекбокси немає сензу масштабувати, бо вони будуть скрізь одинакові. Можливо тільки зробити пару розмірів для різних розширень екранів. Але так фіксовано 20х20
