### ISSUE TITLE
Текстові поля з можливістю варіації

### ISSUE THREAD

**Issue by ProgramMen** [Natus-Vincere-Programming/MindGlow-application#8]
Планую зробити поля для вводу тексту і паролю

**Comment by ProgramMen** [comment]
Для того що б додати нові кольори будемо робити merge з гілкою 6-update-styles чи з гілкою main куди вже залили нові кольори?

**Comment by Co1oR** [comment]
напевно в main

**Comment by Xemii16** [comment]
> Для того що б додати нові кольори будемо робити merge з гілкою 6-update-styles чи з гілкою main куди вже залили нові кольори?

Можна потім порефакторити, або додати нові коміти з головної гілки

**Comment by Xemii16** [comment]
[Figma](https://www.figma.com/design/I5FY5LynQRYEGbldO2objI/Site?node-id=86%3A298&t=UsGuyfW2cSYRmmr8-1)
